# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
        MYSQL_IP: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_USERNAME: root
        MYSQL_DB_NAME: tiktok_test
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup MySql
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.0"
    - run: mysql -u root -e "CREATE DATABASE tiktok_test;"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

